controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_homepage:
    path: /
    controller: App\Controller\UtilisateurController::dashboard
